name: Build and test Node.js application

on:
  push:
    branches: [ "main" ]
 
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
 
  deploy:
   needs: build_and_test
   runs-on: ubuntu-latest

   steps:
    - name: Debug secrets
      run: |
        echo "API KEY length: ${#RENDER_API_KEY}"
        echo "SERVICE ID length: ${#RENDER_SERVICE_ID}"
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}